import React, { useState } from 'react';
import {
  Sparkles,
  FileText,
  Copy,
  Check,
  Download,
  ListOrdered,
  CheckCircle2,
  AlertCircle,
  Clock,
  Loader2,
  Volume2,
  Mic,
  Settings2,
  FileCode,
  ShieldCheck,
} from 'lucide-react';
import { TranscriptionResult, AudioFileMeta } from '../../types';
import { blobToBase64, resampleTo16kMonoWavBlob } from '../../utils/audioProcessor';

interface TranscribeToolProps {
  audioBuffer: AudioBuffer | null;
  audioBlob: Blob | null;
  fileMeta: AudioFileMeta | null;
}

export const TranscribeTool: React.FC<TranscribeToolProps> = ({
  audioBuffer,
  audioBlob,
  fileMeta,
}) => {
  const [loading, setLoading] = useState(false);
  const [statusStep, setStatusStep] = useState<string>('');
  const [result, setResult] = useState<TranscriptionResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [promptCustom, setPromptCustom] = useState('');
  const [showPromptSettings, setShowPromptSettings] = useState(false);

  const handleTranscribe = async () => {
    if (!audioBuffer && !audioBlob) {
      setError('Please upload, record, or load an audio file first.');
      return;
    }

    setLoading(true);
    setError(null);
    setStatusStep('Optimizing speech audio for AI transcription (16kHz mono)...');

    try {
      let base64Data = '';
      let mime = 'audio/wav';

      // 1. Resample to 16kHz mono WAV for high-speed transfer and maximum Gemini accuracy
      if (audioBuffer) {
        const wavBlob = resampleTo16kMonoWavBlob(audioBuffer);
        base64Data = await blobToBase64(wavBlob);
        mime = 'audio/wav';
      } else if (audioBlob) {
        base64Data = await blobToBase64(audioBlob);
        mime = audioBlob.type || 'audio/wav';
      }

      setStatusStep('Transcribing verbatim with Gemini 3.7 Flash & generating notes...');

      const res = await fetch('/api/ai/transcribe', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          audioBase64: base64Data,
          mimeType: mime,
          promptInstruction: promptCustom || undefined,
        }),
      });

      const json = await res.json();
      if (!res.ok) {
        throw new Error(json.error || 'Transcription failed on server.');
      }

      if (json.data) {
        setResult(json.data);
      }
    } catch (err: unknown) {
      const e = err as Error;
      setError(e.message || 'Failed to generate transcription. Please check GEMINI_API_KEY settings.');
    } finally {
      setLoading(false);
      setStatusStep('');
    }
  };

  const handleCopy = () => {
    if (!result) return;
    const text = `# Audio Transcription & AI Summary
Duration: ${fileMeta?.duration ? fileMeta.duration.toFixed(1) + 's' : 'N/A'}

## Summary
${result.summary}

## Key Takeaways
${result.keyPoints?.map((k) => `- ${k}`).join('\n')}

## Action Items
${result.actionItems?.map((a) => `- [ ] ${a}`).join('\n') || 'None'}

## Full Transcript
${result.transcript}`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    if (!result) return;
    const text = `# ${fileMeta?.name || 'Audio'} - Transcript & Notes

**Generated by Submind AI Studio • Engineered by Asfand Mustafa**
- Duration: ${fileMeta?.duration ? fileMeta.duration.toFixed(1) + 's' : 'N/A'}
- Spoken Words: ${result.estimatedWordsCount || 'N/A'}
- Sentiment / Tone: ${result.sentiment || 'Neutral'}

---

## 📌 Executive Summary
${result.summary}

## 🎯 Key Takeaways
${result.keyPoints?.map((k) => `* ${k}`).join('\n')}

## ✅ Action Items
${result.actionItems?.map((a) => `* [ ] ${a}`).join('\n') || 'No explicit action items detected.'}

## 🗣️ Full Verbatim Transcript
${result.transcript}
`;

    const blob = new Blob([text], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileMeta?.name ? fileMeta.name.replace(/\.[^/.]+$/, '') : 'submind'}_transcript.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadText = () => {
    if (!result) return;
    const blob = new Blob([result.transcript], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileMeta?.name ? fileMeta.name.replace(/\.[^/.]+$/, '') : 'submind'}_transcript.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadJson = () => {
    if (!result) return;
    const blob = new Blob([JSON.stringify(result, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${fileMeta?.name ? fileMeta.name.replace(/\.[^/.]+$/, '') : 'submind'}_transcript.json`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-purple-950/60 via-slate-900 to-indigo-950/60 border border-purple-500/30 rounded-2xl p-5 shadow-xl">
        <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-purple-600/30 border border-purple-500/40 flex items-center justify-center text-purple-300">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white flex items-center gap-2">
                <span>AI Audio to Text & Smart Notes</span>
                <span className="text-[10px] bg-purple-500/20 text-purple-300 border border-purple-500/30 px-2 py-0.5 rounded-full font-semibold">
                  Gemini 3.7 Flash
                </span>
              </h2>
              <p className="text-xs text-slate-400">
                Verbatim speech transcription, executive summaries, takeaways, action items, and filler words.
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2 w-full sm:w-auto">
            <button
              onClick={() => setShowPromptSettings(!showPromptSettings)}
              className={`p-2.5 rounded-xl border text-xs font-semibold transition-colors cursor-pointer ${
                showPromptSettings
                  ? 'bg-purple-600/30 border-purple-500/50 text-purple-200'
                  : 'bg-slate-800 border-slate-700 text-slate-400 hover:text-slate-200'
              }`}
              title="Custom Prompt / Instructions"
            >
              <Settings2 className="w-4 h-4" />
            </button>

            <button
              id="start-transcription-btn"
              onClick={handleTranscribe}
              disabled={loading || !audioBuffer}
              className="flex-1 sm:flex-initial flex items-center justify-center gap-2 px-5 py-2.5 rounded-xl bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 text-white text-xs font-bold shadow-lg shadow-purple-600/30 disabled:opacity-50 transition-all cursor-pointer"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>Transcribing Audio...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>Generate Verbatim Transcript</span>
                </>
              )}
            </button>
          </div>
        </div>

        {/* Optional Custom Instructions Input */}
        {showPromptSettings && (
          <div className="mt-4 pt-4 border-t border-purple-500/20 animate-in fade-in duration-200">
            <label className="block text-xs font-semibold text-purple-300 mb-1.5">
              Custom AI Prompt / Instructions (Optional):
            </label>
            <input
              type="text"
              value={promptCustom}
              onChange={(e) => setPromptCustom(e.target.value)}
              placeholder="e.g. Translate into English, highlight meeting decisions, clean filler disfluencies..."
              className="w-full px-3.5 py-2 rounded-xl bg-slate-950/80 border border-purple-500/30 text-slate-200 placeholder-slate-500 text-xs focus:outline-none focus:ring-2 focus:ring-purple-500/50"
            />
          </div>
        )}
      </div>

      {/* Realtime Status Indicator */}
      {loading && statusStep && (
        <div className="bg-purple-950/30 border border-purple-500/30 rounded-xl p-4 text-xs text-purple-300 flex items-center gap-3">
          <Loader2 className="w-4 h-4 animate-spin text-purple-400 flex-shrink-0" />
          <span>{statusStep}</span>
        </div>
      )}

      {/* Error Alert */}
      {error && (
        <div className="bg-rose-950/40 border border-rose-500/40 rounded-xl p-4 text-xs text-rose-300 flex items-start gap-2.5">
          <AlertCircle className="w-4 h-4 text-rose-400 flex-shrink-0 mt-0.5" />
          <div className="flex-1">
            <p className="font-semibold">{error}</p>
            <p className="text-rose-400/80 mt-1">
              Ensure your `GEMINI_API_KEY` is configured in the environment or Settings.
            </p>
          </div>
        </div>
      )}

      {/* Results View */}
      {result ? (
        <div className="space-y-6">
          {/* Quick Actions Bar */}
          <div className="flex flex-wrap items-center justify-between gap-3 bg-slate-900 border border-slate-800 rounded-xl px-4 py-3">
            <div className="flex items-center gap-3 text-xs text-slate-400">
              <span className="flex items-center gap-1">
                <Clock className="w-3.5 h-3.5 text-purple-400" />
                <span>Duration: {fileMeta?.duration ? fileMeta.duration.toFixed(1) + 's' : 'Audio'}</span>
              </span>
              {result.sentiment && (
                <span className="bg-purple-950/60 border border-purple-500/30 text-purple-300 px-2 py-0.5 rounded-full text-[11px]">
                  Tone: {result.sentiment}
                </span>
              )}
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <button
                onClick={handleCopy}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-colors cursor-pointer"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? 'Copied!' : 'Copy Text'}</span>
              </button>
              <button
                onClick={handleDownloadText}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-200 text-xs font-semibold transition-colors cursor-pointer"
              >
                <Download className="w-3.5 h-3.5 text-indigo-400" />
                <span>.TXT</span>
              </button>
              <button
                onClick={handleDownloadMarkdown}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-purple-600 hover:bg-purple-500 text-white text-xs font-semibold transition-colors cursor-pointer"
              >
                <FileText className="w-3.5 h-3.5" />
                <span>Download .MD</span>
              </button>
              <button
                onClick={handleDownloadJson}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs font-semibold transition-colors cursor-pointer"
              >
                <FileCode className="w-3.5 h-3.5 text-purple-400" />
                <span>JSON</span>
              </button>
            </div>
          </div>

          {/* Grid Cards for Summary & Key Points */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Executive Summary */}
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
              <h3 className="text-xs font-bold text-indigo-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                <FileText className="w-3.5 h-3.5" />
                <span>Executive Summary</span>
              </h3>
              <p className="text-sm text-slate-200 leading-relaxed">{result.summary}</p>
            </div>

            {/* Key Takeaways */}
            <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
              <h3 className="text-xs font-bold text-purple-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                <ListOrdered className="w-3.5 h-3.5" />
                <span>Key Takeaways</span>
              </h3>
              <ul className="space-y-1.5 text-xs text-slate-300">
                {result.keyPoints?.map((point, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-purple-400 flex-shrink-0 mt-1.5" />
                    <span>{point}</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>

          {/* Action Items & Filler Words */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Action Items */}
            {result.actionItems && result.actionItems.length > 0 && (
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
                <h3 className="text-xs font-bold text-emerald-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                  <span>Action Items & Follow-ups</span>
                </h3>
                <ul className="space-y-1.5 text-xs text-slate-300">
                  {result.actionItems.map((item, i) => (
                    <li key={i} className="flex items-start gap-2 bg-emerald-950/20 border border-emerald-500/20 rounded-lg p-2">
                      <span className="text-emerald-400 font-bold text-[11px] mt-0.5">✓</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            )}

            {/* Filler Words */}
            {result.fillerWords && result.fillerWords.length > 0 && (
              <div className="bg-slate-900 border border-slate-800 rounded-xl p-4">
                <h3 className="text-xs font-bold text-amber-300 uppercase tracking-wider mb-2 flex items-center gap-1.5">
                  <Volume2 className="w-3.5 h-3.5 text-amber-400" />
                  <span>Filler Words & Pauses Detected</span>
                </h3>
                <div className="flex flex-wrap gap-2">
                  {result.fillerWords.map((fw, i) => (
                    <div
                      key={i}
                      className="flex items-center gap-1.5 bg-slate-800 border border-slate-700 px-2.5 py-1 rounded-lg text-xs"
                    >
                      <span className="font-semibold text-slate-200">"{fw.word}"</span>
                      <span className="bg-amber-500/20 text-amber-300 px-1.5 py-0.5 rounded text-[10px] font-bold">
                        {fw.count}x
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Full Transcript */}
          <div className="bg-slate-900 border border-slate-800 rounded-xl p-5">
            <h3 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-3 flex items-center justify-between">
              <span>Full Verbatim Transcript</span>
              <span className="text-slate-500 text-[11px] font-normal">
                {result.estimatedWordsCount ? `~${result.estimatedWordsCount} words transcribed` : ''}
              </span>
            </h3>
            <div className="bg-slate-950 rounded-xl p-4 text-xs text-slate-200 leading-relaxed whitespace-pre-wrap font-sans max-h-96 overflow-y-auto border border-slate-800/80 selection:bg-purple-500/30">
              {result.transcript}
            </div>
          </div>
        </div>
      ) : (
        <div className="bg-slate-900/50 border border-dashed border-slate-800 rounded-2xl p-8 text-center">
          <FileText className="w-10 h-10 text-slate-600 mx-auto mb-3" />
          <h3 className="text-sm font-semibold text-slate-300">Ready to Transcribe</h3>
          <p className="text-xs text-slate-500 max-w-md mx-auto mt-1">
            Click <strong>Generate Verbatim Transcript</strong> above to transcribe your audio recording into text with structured summaries and key action items.
          </p>
        </div>
      )}
    </div>
  );
};
